language: node_js
node_js:
  - "10"

# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

before_install:
  - curl -sSL https://cli.openfaas.com | sudo sh
  - cd base64 && npm install && cd ..

script:
  - cd base64 && npm run test && cd ..
  - faas-cli build -f base64.yml

notifications:
  email:
    recipients:
      - c-n-i@web.de
    on_success: change
    on_failure: always

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin; fi
  - docker tag cniweb/functions-base64:latest "cniweb/functions-base64:${TRAVIS_COMMIT}"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker push "cniweb/functions-base64:${TRAVIS_COMMIT}"; fi
