language: node_js

# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

before_install:
  - curl -sSL https://cli.openfaas.com | sudo sh

script:
  - cd base64 && npm run test && cd ..
  - faas-cli build

notifications:
  email:
    recipients:
      - templum.dev@gmail.com
    on_success: change
    on_failure: always

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      faas-cli push
    fi
